shops: "168130,168131"   # ID магазинов через запятую
api-version: 3           # Версия API TradeMC
check-interval-seconds: 60  # Интервал проверки новых покупок в секундах
retry-attempts: 3        # Количество попыток повтора при ошибке
retry-delay-seconds: 5   # Задержка между попытками в секундах