# ID вашего магазина на TradeMC (обязательно)
shops: "YOUR_SHOP_ID"  # Замените "YOUR_SHOP_ID" на реальный ID вашего магазина

# Ключ вашего магазина (обязательно, только если callback.enabled: true)
callback-key: ""

# Настройки проверки покупок
check-interval-seconds: 60 # Как часто проверять новые покупки
retry-attempts: 3         # Сколько раз пытаться повторить при ошибке
retry-delay-seconds: 5    # Пауза между повторами

# Настройки базы данных (необязательно)
mysql:
  enabled: false         # Включить/выключить MySQL
  host: "localhost"      # Адрес базы данных
  port: 3306            # Порт базы данных
  database: "trade_db"  # Имя базы данных
  user: "root"          # Пользователь
  password: "password"  # Пароль

# Настройки callback (для продвинутых пользователей)
callback:
  enabled: false        # Включить/выключить callback
  host: "0.0.0.0"        # IP для прослушивания
  port: 8080             # Порт
  path: "/tradecallback" # Путь

# Версия API TradeMC
api-version: 3

# Настройки логирования
logging:
  enabled: true
  max-history: 1000  # Максимальное количество записей в логе