shops: "0"  # Можно "168130,168131" если несколько
api-version: 3 # Версия API TradeMC
check-interval-seconds: 60 # Интервал проверки новых покупок в секундах
retry-attempts: 3 # Количество попыток повтора при ошибке
retry-delay-seconds: 5 # Задержка между попытками в секундах

callback: # Настройки обратного вызова
  enabled: true # Включен ли обратный вызов
  host: "0.0.0.0"            # IP адрес для прослушивания, "0.0.0.0" — все интерфейсы
  port: 8080                 # Порт для обратного вызова
  path: "/tradecallback"     # Путь для обработки запросов

callback-key: "Your_Shop_Secret_Key"  # Ключ для проверки hash

mysql: # MySQL настройки
  enabled: false # Включен ли MySQL
  host: "localhost" # Хост MySQL
  port: 3306 # Порт MySQL
  database: "trade_db" # Имя базы данных
  user: "trade_user" # Пользователь MySQL
  password: "secret" # Пароль MySQL